defaults: &defaults
  api:
    port: 3000
    server_base_url: http://localhost:3000
    server_base_path: /api/usermanagementapi
  logger:
    name: User Management API
    level: debug
    levels:
      trace:
      debug:
      info: STDOUT
      warn: STDOUT
      error: STDOUT
      fatal: STDOUT

development:
  <<: *defaults

beta:
  <<: *defaults

production:
  <<: *defaults
